<div data-role="content">
    <script type="text/javascript" src="scripts/facebook.js"></script>

    <table border="0px" width="auto">
        <tr>
            <td>
                <div id="SeiteUndLikes"></div>
            </td>
        </tr>
        <tr>
            <td>
                <div id="Veranstaltungen">Dies sind die
                    Top 3 aktuell kontroversen Nachrichten:
                </div>
            </td>
        </tr>
        <tr>
            <td class="tabellenlinie">
                <table border="0px">
                    <tr>
                        <td colspan=2><p id="M1"></p></td>
                    </tr>
                    <tr>
                        <td align="left"><div id="M1Likes"><img src="imgs/social_media/facebook/ilike.png"></div></td>
                        <td align="right"><div id="M1Comments"><img src="imgs/social_media/facebook/comments.png"></div></td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td class="tabellenlinie">
                <table border="0px">
                    <tr>
                        <td colspan=2><p id="M2"></p></td>
                    </tr>
                    <tr>
                        <td align="left"><div id="M2Likes"><img src="imgs/social_media/facebook/ilike.png"></div></td>
                        <td align="right"><div id="M2Comments"><img src="imgs/social_media/facebook/comments.png"></div></td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td class="tabellenlinie">
                <table border="0px">
                    <tr>
                        <td colspan=2><p id="M3"></p></td>
                    </tr>
                    <tr>
                        <td align="left"><div id="M3Likes"><img src="imgs/social_media/facebook/ilike.png"></div></td>
                        <td align="right"><div id="M3Comments"><img src="imgs/social_media/facebook/comments.png"></div></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>