<div data-role="content">
    <fieldset class="ui-grid-a">
        <div class="ui-block-a"><a href="#social_facebook" data-role="button"><img src="imgs/social_media/facebook.png"></a></div>
        <div class="ui-block-b"><a href="#social_twitter" data-role="button"><img src="imgs/social_media/twitter.png"></a></div>
        <div class="ui-block-a"><a href="#social_google" data-role="button"><img src="imgs/social_media/google.png"></a></div>
        <div class="ui-block-b"><a href="#social_xing" data-role="button"><img src="imgs/social_media/xing.png"></a></div>
        <div class="ui-block-a"><a href="#social_linkedin" data-role="button"><img src="imgs/social_media/linkedin.png"></a></div>
        <div class="ui-block-b"><a href="#social_rss" data-role="button"><img src="imgs/social_media/rss.png"></a></div>
    </fieldset>
</div>